# Generated by Django 4.2.1 on 2023-06-02 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Specimen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='име')),
                ('points', models.IntegerField(default=0, verbose_name='точки')),
                ('category', models.CharField(choices=[('PLANT', 'растение'), ('MUSHROOM', 'гъба'), ('ANIMAL', 'животно'), ('INSECT', 'насекомо')], max_length=10, verbose_name='тип')),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'вид',
                'verbose_name_plural': 'видове',
            },
        ),
        migrations.CreateModel(
            name='SpecimenSighting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='specimens/', verbose_name='изображение')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='ширина')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='дължина')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='време на създаване')),
                ('specimen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='specimens.specimen', verbose_name='вид')),
            ],
            options={
                'verbose_name': 'забелязване на вид',
            },
        ),
    ]
