# Generated by Django 4.2.1 on 2023-06-03 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specimens', '0003_alter_specimensighting_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='specimensighting',
            name='europeana_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
