# Generated by Django 4.2.1 on 2023-06-07 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specimens', '0004_specimensighting_europeana_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='specimen',
            name='specimen_class',
            field=models.CharField(choices=[('COMMON', 'често срещано'), ('RARE', 'рядко срещано'), ('EPIC', 'епично'), ('LEGENDARY', 'легендарно')], default='COMMON', max_length=10, verbose_name='клас'),
            preserve_default=False,
        ),
    ]
