# Generated by Django 4.2.1 on 2023-06-07 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specimens', '0005_specimen_specimen_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specimen',
            name='category',
            field=models.CharField(choices=[('PLANT', 'растение'), ('MUSHROOM', 'гъба'), ('ANIMAL', 'животно'), ('INSECT', 'насекомо'), ('OTHER', 'друг')], max_length=10, verbose_name='тип'),
        ),
    ]
